
package org.apache.catalina.security;

import org.junit.Test;

public class TestSecurityClassLoad {

    @Test
    public void testLoad() throws Exception {
        // Note that this will fail if you run it from within Eclipse. This is
        // because one of the loaded classes (AccessLogValve$3) is a synthetic
        // class generated by javac but not by the JDT compiler. Behaviour with
        // other IDEs is currently unknown.
        SecurityClassLoad.securityClassLoad(
            Thread.currentThread().getContextClassLoader(), false);
    }
}
