
/* Generated By:JJTree: Do not edit this line. AstMapEntry.java Version 4.3 */
package org.apache.el.parser;

public
class AstMapEntry extends SimpleNode {
  public AstMapEntry(int id) {
    super(id);
  }
}
/* JavaCC - OriginalChecksum=6a7910e58a583371769800554113a8d3 (do not edit this line) */
